export const orderStatus = {
    FILLED: 'FILLED',
    PARTIALLY_FILLED: 'PARTIALLY_FILLED',
    CANCELED: 'CANCELED',
    REJECTED: 'REJECTED',
    NEW: 'NEW'
}

export const orderTypes = {
    STOP_LOSS: "STOP_LOSS",
    STOP_LOSS_LIMIT: "STOP_LOSS_LIMIT",
    TAKE_PROFIT: "TAKE_PROFIT",
    TAKE_PROFIT_LIMIT: "TAKE_PROFIT_LIMIT",
    MARKET: "MARKET",
    LIMIT: "LIMIT",
    ICEBERG: "ICEBERG",
    TRAILING_STOP: "TRAILING_STOP"
}