export default {
    ALERT_EMAIL: "ALERT_EMAIL",
    ALERT_SMS: "ALERT_SMS",
    ALERT_TELEGRAM: "ALERT_TELEGRAM",
    ORDER: "ORDER",
    GRID: "GRID",
    WITHDRAW: "WITHDRAW",
    TRAILING: "TRAILING"
}